import Head from 'next/head'

import styles from './Home.module.css'

import Community from '@/svgs/Community/Community'

const Home = () => {

  return (
    <div className='page aspect'>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className={styles.heading}>
          <div className={styles.titleContainer}>
            <h1 className={styles.title}>Community Connector</h1>
            <h2 className={styles.subtitle}>Connecting community to start giving..</h2>
          </div>

          <div className={styles.imageContainer}>
            <Community primaryColor="#EE6F1D" secondaryColor="#2c6d89" />
          </div>

        </div>

      </main>


    </div>
  )
}


export default Home
